//
//  EmojiData.swift
//  SharedKit
//
//  Searchable emoji database with categories and keywords.
//

import Foundation

public enum EmojiCategory: String, CaseIterable, Identifiable, Sendable {
    case smileys    = "Smileys"
    case people     = "People"
    case animals    = "Animals"
    case food       = "Food"
    case activities = "Activity"
    case travel     = "Travel"
    case objects    = "Objects"
    case symbols    = "Symbols"
    case flags      = "Flags"

    public var id: String { rawValue }

    public var icon: String {
        switch self {
        case .smileys:    return "😊"
        case .people:     return "👋"
        case .animals:    return "🐱"
        case .food:       return "🍕"
        case .activities: return "⚽"
        case .travel:     return "✈️"
        case .objects:    return "💡"
        case .symbols:    return "❤️"
        case .flags:      return "🇧🇩"
        }
    }
}

public struct EmojiItem: Identifiable, Sendable, Hashable {
    public var id: String { emoji }
    public let emoji: String
    public let name: String
    public let keywords: [String]
    public let category: EmojiCategory

    public init(_ emoji: String, _ name: String, _ keywords: [String], _ category: EmojiCategory) {
        self.emoji = emoji
        self.name = name
        self.keywords = keywords
        self.category = category
    }

    public func matches(query: String) -> Bool {
        let q = query.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if q.isEmpty { return true }
        if emoji == q { return true }
        if name.lowercased().contains(q) { return true }
        return keywords.contains { $0.lowercased().contains(q) }
    }
}

public enum EmojiCatalog {
    public static let all: [EmojiItem] = [
        // MARK: - Smileys
        EmojiItem("😀", "Grinning Face", ["happy", "smile", "grin"], .smileys),
        EmojiItem("😃", "Grinning Face with Big Eyes", ["happy", "joy", "smile"], .smileys),
        EmojiItem("😄", "Grinning Face with Smiling Eyes", ["happy", "laugh", "smile"], .smileys),
        EmojiItem("😁", "Beaming Face", ["grin", "smile", "teeth"], .smileys),
        EmojiItem("😆", "Grinning Squinting Face", ["laugh", "haha", "lol"], .smileys),
        EmojiItem("😅", "Grinning Face with Sweat", ["relief", "nervous", "sweat"], .smileys),
        EmojiItem("🤣", "Rolling on the Floor Laughing", ["rofl", "lmao", "hilarious"], .smileys),
        EmojiItem("😂", "Face with Tears of Joy", ["cry", "laugh", "happy", "tears"], .smileys),
        EmojiItem("🙂", "Slightly Smiling Face", ["smile", "calm", "okay"], .smileys),
        EmojiItem("🙃", "Upside-Down Face", ["sarcasm", "silly", "irony"], .smileys),
        EmojiItem("😉", "Winking Face", ["wink", "flirt", "joke"], .smileys),
        EmojiItem("😊", "Smiling Face with Smiling Eyes", ["blush", "warm", "friendly"], .smileys),
        EmojiItem("😇", "Smiling Face with Halo", ["angel", "innocent", "pure"], .smileys),
        EmojiItem("🥰", "Smiling Face with Hearts", ["love", "crush", "adore", "heart"], .smileys),
        EmojiItem("😍", "Heart Eyes", ["love", "heart", "attracted", "kiss"], .smileys),
        EmojiItem("🤩", "Star-Struck", ["star", "excited", "wow", "amazing"], .smileys),
        EmojiItem("😘", "Face Blowing a Kiss", ["kiss", "love", "affection"], .smileys),
        EmojiItem("😗", "Kissing Face", ["kiss", "duck"], .smileys),
        EmojiItem("😚", "Kissing Face with Closed Eyes", ["kiss", "love"], .smileys),
        EmojiItem("😋", "Face Savoring Food", ["yum", "delicious", "tongue", "tasty"], .smileys),
        EmojiItem("😛", "Face with Tongue", ["playful", "silly", "joke"], .smileys),
        EmojiItem("😜", "Winking Face with Tongue", ["crazy", "party", "wink"], .smileys),
        EmojiItem("🤪", "Zany Face", ["wild", "crazy", "silly"], .smileys),
        EmojiItem("😝", "Squinting Face with Tongue", ["prank", "lol", "tongue"], .smileys),
        EmojiItem("🤑", "Money-Mouth Face", ["cash", "rich", "dollar", "wealth"], .smileys),
        EmojiItem("🤗", "Smiling Face with Open Hands", ["hug", "welcome", "warmth"], .smileys),
        EmojiItem("🤭", "Face with Hand Over Mouth", ["oops", "giggle", "secret"], .smileys),
        EmojiItem("🤫", "Shushing Face", ["quiet", "shh", "silence", "secret"], .smileys),
        EmojiItem("🤔", "Thinking Face", ["hmm", "think", "wonder", "ponder"], .smileys),
        EmojiItem("🤐", "Zipper-Mouth Face", ["shut", "silent", "secret"], .smileys),
        EmojiItem("🤨", "Face with Raised Eyebrow", ["skeptic", "suspicious", "doubt"], .smileys),
        EmojiItem("😐", "Neutral Face", ["meh", "okay", "straight"], .smileys),
        EmojiItem("😑", "Expressionless Face", ["deadpan", "unimpressed"], .smileys),
        EmojiItem("😶", "Face Without Mouth", ["mute", "speechless"], .smileys),
        EmojiItem("😏", "Smirking Face", ["smug", "flirt", "cocky"], .smileys),
        EmojiItem("😒", "Unamused Face", ["annoyed", "bored", "dissatisfied"], .smileys),
        EmojiItem("🙄", "Face with Rolling Eyes", ["eyeroll", "whatever", "bored"], .smileys),
        EmojiItem("😬", "Grimacing Face", ["awkward", "nervous", "oops"], .smileys),
        EmojiItem("🤥", "Lying Face", ["pinocchio", "lie", "dishonest"], .smileys),
        EmojiItem("😌", "Relieved Face", ["relief", "peace", "calm"], .smileys),
        EmojiItem("😔", "Pensive Face", ["sad", "thoughtful", "sorrow"], .smileys),
        EmojiItem("😪", "Sleepy Face", ["tired", "rest", "sleep"], .smileys),
        EmojiItem("🤤", "Drooling Face", ["hungry", "craving", "drool"], .smileys),
        EmojiItem("😴", "Sleeping Face", ["zzz", "sleep", "night", "tired"], .smileys),
        EmojiItem("😷", "Face with Medical Mask", ["sick", "doctor", "virus", "covid"], .smileys),
        EmojiItem("🤒", "Face with Thermometer", ["sick", "fever", "ill"], .smileys),
        EmojiItem("🤕", "Face with Head-Bandage", ["hurt", "injured", "pain"], .smileys),
        EmojiItem("🤢", "Nauseated Face", ["gross", "vomit", "disgust"], .smileys),
        EmojiItem("🤮", "Face Vomiting", ["sick", "puke", "throwup"], .smileys),
        EmojiItem("🤧", "Sneezing Face", ["sneeze", "allergy", "cold"], .smileys),
        EmojiItem("🥵", "Hot Face", ["heat", "summer", "warm", "sweat"], .smileys),
        EmojiItem("🥶", "Cold Face", ["freeze", "winter", "ice"], .smileys),
        EmojiItem("🥴", "Woozy Face", ["dizzy", "drunk", "tired"], .smileys),
        EmojiItem("😵", "Face with Crossed-Out Eyes", ["shocked", "dead", "knockout"], .smileys),
        EmojiItem("🤯", "Exploding Head", ["mindblown", "shock", "wow"], .smileys),
        EmojiItem("🥳", "Partying Face", ["celebration", "birthday", "party", "cheers"], .smileys),
        EmojiItem("😎", "Smiling Face with Sunglasses", ["cool", "chill", "summer", "boss"], .smileys),
        EmojiItem("🤓", "Nerd Face", ["geek", "smart", "glasses", "study"], .smileys),
        EmojiItem("🧐", "Face with Monocle", ["examine", "curious", "classy"], .smileys),
        EmojiItem("😕", "Confused Face", ["what", "unsure", "doubt"], .smileys),
        EmojiItem("😟", "Worried Face", ["scared", "nervous", "concern"], .smileys),
        EmojiItem("🙁", "Slightly Frowning Face", ["sad", "frown"], .smileys),
        EmojiItem("😮", "Face with Open Mouth", ["surprise", "wow", "gasp"], .smileys),
        EmojiItem("😯", "Hushed Face", ["quiet", "shock", "surprise"], .smileys),
        EmojiItem("😲", "Astonished Face", ["shocked", "amazed", "omg"], .smileys),
        EmojiItem("😳", "Flushed Face", ["blush", "embarrassed", "wideeyes"], .smileys),
        EmojiItem("🥺", "Pleading Face", ["puppy", "please", "beg", "cute"], .smileys),
        EmojiItem("😦", "Frowning Face with Open Mouth", ["shock", "fear"], .smileys),
        EmojiItem("😨", "Fearful Face", ["scared", "spooked", "anxious"], .smileys),
        EmojiItem("😰", "Anxious Face with Sweat", ["panic", "nervous"], .smileys),
        EmojiItem("😥", "Sad but Relieved Face", ["phew", "close"], .smileys),
        EmojiItem("😢", "Crying Face", ["sad", "tear", "unhappy"], .smileys),
        EmojiItem("😭", "Loudly Crying Face", ["bawling", "sad", "omg", "tears"], .smileys),
        EmojiItem("😱", "Face Screaming in Fear", ["scream", "munch", "horror"], .smileys),
        EmojiItem("😖", "Confounded Face", ["frustrated", "stress"], .smileys),
        EmojiItem("😣", "Persevering Face", ["struggle", "trying"], .smileys),
        EmojiItem("😞", "Disappointed Face", ["letdown", "sad"], .smileys),
        EmojiItem("😓", "Downcast Face with Sweat", ["hard work", "stress"], .smileys),
        EmojiItem("😩", "Weary Face", ["exhausted", "tired", "done"], .smileys),
        EmojiItem("😫", "Tired Face", ["sleepy", "fedup"], .smileys),
        EmojiItem("🥱", "Yawning Face", ["bored", "sleepy", "night"], .smileys),
        EmojiItem("😤", "Face with Steam From Nose", ["angry", "triumph", "proud"], .smileys),
        EmojiItem("😡", "Enraged Face", ["angry", "pissed", "mad", "red"], .smileys),
        EmojiItem("😠", "Angry Face", ["mad", "cross", "grumpy"], .smileys),
        EmojiItem("🤬", "Face with Symbols on Mouth", ["curse", "swear", "furious"], .smileys),
        EmojiItem("😈", "Smiling Face with Horns", ["devil", "evil", "naughty"], .smileys),
        EmojiItem("👿", "Angry Face with Horns", ["demon", "devil", "mad"], .smileys),
        EmojiItem("💀", "Skull", ["dead", "skeleton", "death", "lol"], .smileys),
        EmojiItem("💩", "Pile of Poo", ["poop", "dung", "crap"], .smileys),
        EmojiItem("🤡", "Clown Face", ["circus", "fool", "joke"], .smileys),
        EmojiItem("👻", "Ghost", ["spooky", "halloween", "haunt"], .smileys),
        EmojiItem("👽", "Alien", ["ufo", "space", "extraterrestrial"], .smileys),
        EmojiItem("🤖", "Robot", ["bot", "ai", "machine"], .smileys),

        // MARK: - People & Gestures
        EmojiItem("👋", "Waving Hand", ["hello", "bye", "hi", "wave"], .people),
        EmojiItem("🤚", "Raised Back of Hand", ["backhand", "stop"], .people),
        EmojiItem("🖐️", "Hand with Fingers Splayed", ["five", "palm"], .people),
        EmojiItem("✋", "Raised Hand", ["stop", "highfive", "halt"], .people),
        EmojiItem("🖖", "Vulcan Salute", ["spock", "star trek"], .people),
        EmojiItem("👌", "OK Hand", ["perfect", "good", "fine", "agree"], .people),
        EmojiItem("🤌", "Pinched Fingers", ["italian", "chef", "what"], .people),
        EmojiItem("🤏", "Pinching Hand", ["small", "tiny", "little"], .people),
        EmojiItem("✌️", "Victory Hand", ["peace", "two", "win"], .people),
        EmojiItem("🤞", "Crossed Fingers", ["luck", "hope", "wish"], .people),
        EmojiItem("🤟", "Love-You Gesture", ["ily", "rock", "love"], .people),
        EmojiItem("🤘", "Sign of the Horns", ["rock", "metal", "party"], .people),
        EmojiItem("🤙", "Call Me Hand", ["shaka", "hang loose", "phone"], .people),
        EmojiItem("👈", "Backhand Index Pointing Left", ["left", "point"], .people),
        EmojiItem("👉", "Backhand Index Pointing Right", ["right", "point"], .people),
        EmojiItem("👆", "Backhand Index Pointing Up", ["up", "point"], .people),
        EmojiItem("🖕", "Middle Finger", ["rude", "f**k"], .people),
        EmojiItem("👇", "Backhand Index Pointing Down", ["down", "below"], .people),
        EmojiItem("☝️", "Index Pointing Up", ["one", "first", "question"], .people),
        EmojiItem("👍", "Thumbs Up", ["yes", "like", "approve", "good", "agree"], .people),
        EmojiItem("👎", "Thumbs Down", ["no", "dislike", "bad", "disapprove"], .people),
        EmojiItem("✊", "Raised Fist", ["power", "punch", "strength"], .people),
        EmojiItem("👊", "Oncoming Fist", ["fistbump", "bro", "punch"], .people),
        EmojiItem("🤛", "Left-Facing Fist", ["fistbump"], .people),
        EmojiItem("🤜", "Right-Facing Fist", ["fistbump"], .people),
        EmojiItem("👏", "Clapping Hands", ["applause", "bravo", "praise"], .people),
        EmojiItem("🙌", "Raising Hands", ["celebrate", "hooray", "hallelujah"], .people),
        EmojiItem("👐", "Open Hands", ["open", "care"], .people),
        EmojiItem("🤲", "Palms Up Together", ["dua", "pray", "prayer", "bengali"], .people),
        EmojiItem("🤝", "Handshake", ["deal", "agreement", "partner", "meeting"], .people),
        EmojiItem("🙏", "Folded Hands", ["pray", "thank you", "please", "namaste", "dua"], .people),
        EmojiItem("✍️", "Writing Hand", ["write", "author", "lekhi", "pen"], .people),
        EmojiItem("💅", "Nail Polish", ["beauty", "cosmetics", "slay"], .people),
        EmojiItem("🤳", "Selfie", ["camera", "phone", "photo"], .people),
        EmojiItem("💪", "Flexed Biceps", ["muscle", "strong", "gym", "power", "flex"], .people),

        // MARK: - Animals & Nature
        EmojiItem("🐶", "Dog Face", ["puppy", "pet", "bark"], .animals),
        EmojiItem("🐱", "Cat Face", ["kitten", "meow", "pet"], .animals),
        EmojiItem("🐭", "Mouse Face", ["rat", "cheese"], .animals),
        EmojiItem("🐹", "Hamster", ["pet", "cute"], .animals),
        EmojiItem("🐰", "Rabbit Face", ["bunny", "easter"], .animals),
        EmojiItem("🦊", "Fox", ["cunning", "wild"], .animals),
        EmojiItem("🐻", "Bear", ["teddy", "wild", "grizzly"], .animals),
        EmojiItem("🐼", "Panda", ["bamboo", "china", "cute"], .animals),
        EmojiItem("🐨", "Koala", ["australia", "cute"], .animals),
        EmojiItem("🐯", "Tiger Face", ["royal", "bengal tiger", "shunderban", "bangladesh"], .animals),
        EmojiItem("🦁", "Lion", ["king", "safari", "brave"], .animals),
        EmojiItem("🐮", "Cow Face", ["milk", "beef", "moo"], .animals),
        EmojiItem("🐷", "Pig Face", ["oink", "pork"], .animals),
        EmojiItem("🐸", "Frog", ["amphibian", "ribbit"], .animals),
        EmojiItem("🐵", "Monkey Face", ["ape", "banana", "chimp"], .animals),
        EmojiItem("🐔", "Chicken", ["hen", "poultry", "bird"], .animals),
        EmojiItem("🐧", "Penguin", ["antarctica", "bird", "cold"], .animals),
        EmojiItem("🐦", "Bird", ["tweet", "nature", "fly"], .animals),
        EmojiItem("🐤", "Baby Chick", ["cute", "yellow"], .animals),
        EmojiItem("🦆", "Duck", ["quack", "water"], .animals),
        EmojiItem("🦅", "Eagle", ["usa", "bird", "fly"], .animals),
        EmojiItem("🦉", "Owl", ["wise", "night", "bird"], .animals),
        EmojiItem("🦇", "Bat", ["vampire", "night", "halloween"], .animals),
        EmojiItem("🐺", "Wolf", ["howl", "pack", "wild"], .animals),
        EmojiItem("🐗", "Boar", ["wild pig"], .animals),
        EmojiItem("🐴", "Horse Face", ["pony", "ride"], .animals),
        EmojiItem("🦄", "Unicorn", ["magic", "fantasy"], .animals),
        EmojiItem("🐝", "Honeybee", ["bee", "honey", "insect"], .animals),
        EmojiItem("🐛", "Bug", ["insect", "caterpillar"], .animals),
        EmojiItem("🦋", "Butterfly", ["wings", "pretty", "nature"], .animals),
        EmojiItem("🐌", "Snail", ["slow", "nature"], .animals),
        EmojiItem("🐞", "Lady Beetle", ["ladybug", "insect"], .animals),
        EmojiItem("🐜", "Ant", ["insect", "work"], .animals),
        EmojiItem("🦟", "Mosquito", ["bug", "dengue", "bite"], .animals),
        EmojiItem("🐢", "Turtle", ["tortoise", "slow", "reptile"], .animals),
        EmojiItem("🐍", "Snake", ["python", "cobra", "reptile"], .animals),
        EmojiItem("🦎", "Lizard", ["reptile", "gecko"], .animals),
        EmojiItem("🦖", "T-Rex", ["dinosaur", "jurassic"], .animals),
        EmojiItem("🦕", "Sauropod", ["dinosaur"], .animals),
        EmojiItem("🐙", "Octopus", ["sea", "tentacles", "ocean"], .animals),
        EmojiItem("🦑", "Squid", ["sea", "calamari"], .animals),
        EmojiItem("🦐", "Shrimp", ["seafood", "prawn", "chingri"], .animals),
        EmojiItem("🦞", "Lobster", ["seafood", "crab"], .animals),
        EmojiItem("🦀", "Crab", ["ocean", "seafood"], .animals),
        EmojiItem("🐡", "Blowfish", ["pufferfish", "ocean"], .animals),
        EmojiItem("🐠", "Tropical Fish", ["fish", "nemo", "ocean"], .animals),
        EmojiItem("🐟", "Fish", ["mach", "ilish", "hilsa", "bangla"], .animals),
        EmojiItem("🐬", "Dolphin", ["sea", "mammal"], .animals),
        EmojiItem("🐳", "Spouting Whale", ["whale", "ocean", "sea"], .animals),
        EmojiItem("🦈", "Shark", ["ocean", "predator", "teeth"], .animals),
        EmojiItem("🐊", "Crocodile", ["alligator", "reptile"], .animals),
        EmojiItem("🌲", "Evergreen Tree", ["pine", "tree", "forest"], .animals),
        EmojiItem("🌳", "Deciduous Tree", ["tree", "nature", "green"], .animals),
        EmojiItem("🌴", "Palm Tree", ["beach", "tropical", "summer"], .animals),
        EmojiItem("🌱", "Seedling", ["plant", "grow", "nature"], .animals),
        EmojiItem("🌿", "Herb", ["leaf", "plant", "green"], .animals),
        EmojiItem("☘️", "Shamrock", ["clover", "irish", "luck"], .animals),
        EmojiItem("🍀", "Four Leaf Clover", ["luck", "lucky"], .animals),
        EmojiItem("🎋", "Tanabata Tree", ["wishing tree"], .animals),
        EmojiItem("🍃", "Leaf Fluttering in Wind", ["leaf", "autumn", "fall"], .animals),
        EmojiItem("🍂", "Fallen Leaf", ["autumn", "season"], .animals),
        EmojiItem("🍁", "Maple Leaf", ["canada", "autumn"], .animals),
        EmojiItem("🍄", "Mushroom", ["fungus", "shroom"], .animals),
        EmojiItem("🌸", "Cherry Blossom", ["flower", "sakura", "pink", "spring"], .animals),
        EmojiItem("🌹", "Rose", ["flower", "red", "love", "romance"], .animals),
        EmojiItem("🌺", "Hibiscus", ["flower", "tropical"], .animals),
        EmojiItem("🌻", "Sunflower", ["flower", "yellow", "sun"], .animals),
        EmojiItem("🌼", "Blossom", ["flower", "yellow"], .animals),
        EmojiItem("🌷", "Tulip", ["flower", "spring"], .animals),

        // MARK: - Food & Drink
        EmojiItem("🍏", "Green Apple", ["fruit", "apple", "diet"], .food),
        EmojiItem("🍎", "Red Apple", ["fruit", "apple", "sweet"], .food),
        EmojiItem("🍐", "Pear", ["fruit"], .food),
        EmojiItem("🍊", "Tangerine", ["orange", "citrus", "fruit"], .food),
        EmojiItem("🍋", "Lemon", ["sour", "citrus", "fruit"], .food),
        EmojiItem("🍌", "Banana", ["fruit", "potassium", "kela"], .food),
        EmojiItem("🍉", "Watermelon", ["summer", "fruit", "melon", "tormuj"], .food),
        EmojiItem("🍇", "Grapes", ["fruit", "wine", "angur"], .food),
        EmojiItem("🍓", "Strawberry", ["fruit", "berry", "sweet"], .food),
        EmojiItem("🫐", "Blueberries", ["berry", "fruit"], .food),
        EmojiItem("🍈", "Melon", ["fruit", "sweet"], .food),
        EmojiItem("🍒", "Cherries", ["fruit", "pair"], .food),
        EmojiItem("🍑", "Peach", ["fruit", "butt"], .food),
        EmojiItem("🥭", "Mango", ["fruit", "aam", "bangladesh", "rajshahi"], .food),
        EmojiItem("🍍", "Pineapple", ["fruit", "anaras", "tropical"], .food),
        EmojiItem("🥥", "Coconut", ["fruit", "narkel", "tropical"], .food),
        EmojiItem("🥝", "Kiwi Fruit", ["fruit", "green"], .food),
        EmojiItem("🍅", "Tomato", ["vegetable", "red", "salad"], .food),
        EmojiItem("🥑", "Avocado", ["healthy", "guacamole"], .food),
        EmojiItem("🥦", "Broccoli", ["vegetable", "green"], .food),
        EmojiItem("🥒", "Cucumber", ["vegetable", "salad", "sosha"], .food),
        EmojiItem("🌶️", "Hot Pepper", ["spicy", "chili", "morich", "jhal"], .food),
        EmojiItem("🌽", "Ear of Corn", ["corn", "maize"], .food),
        EmojiItem("🥕", "Carrot", ["vegetable", "gajor"], .food),
        EmojiItem("🧄", "Garlic", ["spice", "roshun", "cook"], .food),
        EmojiItem("🧅", "Onion", ["spice", "peyaj", "cook"], .food),
        EmojiItem("🥔", "Potato", ["alu", "vegetable"], .food),
        EmojiItem("🍠", "Roasted Sweet Potato", ["yam", "potato"], .food),
        EmojiItem("🥐", "Croissant", ["bread", "bakery", "french"], .food),
        EmojiItem("🍞", "Bread", ["ruti", "toast", "bakery"], .food),
        EmojiItem("🥖", "Baguette Bread", ["french bread"], .food),
        EmojiItem("🧀", "Cheese Wedge", ["cheese", "dairy"], .food),
        EmojiItem("🥚", "Egg", ["dim", "breakfast", "protein"], .food),
        EmojiItem("🍳", "Cooking", ["fried egg", "breakfast"], .food),
        EmojiItem("🥞", "Pancakes", ["breakfast", "syrup"], .food),
        EmojiItem("🧇", "Waffle", ["breakfast"], .food),
        EmojiItem("🥓", "Bacon", ["breakfast", "meat"], .food),
        EmojiItem("🥩", "Cut of Meat", ["steak", "beef", "goshto"], .food),
        EmojiItem("🍗", "Poultry Leg", ["chicken", "drumstick", "grill"], .food),
        EmojiItem("🍖", "Meat on Bone", ["meat", "bbq"], .food),
        EmojiItem("🍔", "Hamburger", ["burger", "fast food", "beef"], .food),
        EmojiItem("🍟", "French Fries", ["chips", "fast food", "potato"], .food),
        EmojiItem("🍕", "Pizza", ["cheese", "italian", "slice"], .food),
        EmojiItem("🌭", "Hot Dog", ["sausage", "fast food"], .food),
        EmojiItem("🥪", "Sandwich", ["bread", "lunch"], .food),
        EmojiItem("🌮", "Taco", ["mexican", "food"], .food),
        EmojiItem("🌯", "Burrito", ["mexican", "wrap"], .food),
        EmojiItem("🥙", "Stuffed Flatbread", ["shawarma", "kebab"], .food),
        EmojiItem("🧆", "Falafel", ["middle eastern", "food"], .food),
        EmojiItem("🍜", "Steaming Bowl", ["noodles", "ramen", "soup"], .food),
        EmojiItem("🍲", "Pot of Food", ["curry", "stew", "torkari"], .food),
        EmojiItem("🍛", "Curry Rice", ["biryani", "curry", "bhat", "polao"], .food),
        EmojiItem("🍚", "Cooked Rice", ["rice", "bhat", "grain"], .food),
        EmojiItem("🍙", "Rice Ball", ["onigiri", "sushi"], .food),
        EmojiItem("🍣", "Sushi", ["japanese", "fish"], .food),
        EmojiItem("🥟", "Dumpling", ["momo", "dimsum"], .food),
        EmojiItem("🍤", "Fried Shrimp", ["tempura", "seafood"], .food),
        EmojiItem("🎂", "Birthday Cake", ["cake", "party", "celebration", "sweet"], .food),
        EmojiItem("🍰", "Shortcake", ["cake", "dessert", "sweet"], .food),
        EmojiItem("🧁", "Cupcake", ["dessert", "sweet"], .food),
        EmojiItem("🍦", "Soft Ice Cream", ["ice cream", "sweet", "dessert"], .food),
        EmojiItem("🍧", "Shaved Ice", ["dessert", "ice"], .food),
        EmojiItem("🍨", "Ice Cream", ["dessert", "sweet"], .food),
        EmojiItem("🍩", "Doughnut", ["donut", "sweet"], .food),
        EmojiItem("🍪", "Cookie", ["biscuit", "sweet", "chocolate"], .food),
        EmojiItem("🍫", "Chocolate Bar", ["candy", "sweet"], .food),
        EmojiItem("🍬", "Candy", ["sweet", "sugar"], .food),
        EmojiItem("🍭", "Lollipop", ["candy", "sweet"], .food),
        EmojiItem("🍯", "Honey Pot", ["honey", "sweet"], .food),
        EmojiItem("☕", "Hot Beverage", ["coffee", "tea", "cha", "cafe"], .food),
        EmojiItem("🍵", "Teacup Without Handle", ["green tea", "matcha"], .food),
        EmojiItem("🧃", "Beverage Box", ["juice", "drink"], .food),
        EmojiItem("🥤", "Cup with Straw", ["soda", "drink", "cola"], .food),
        EmojiItem("🧋", "Bubble Tea", ["boba", "milk tea"], .food),
        EmojiItem("🥛", "Glass of Milk", ["dairy", "drink", "dudh"], .food),

        // MARK: - Activities
        EmojiItem("⚽", "Soccer Ball", ["football", "fifa", "sport", "khela"], .activities),
        EmojiItem("🏀", "Basketball", ["nba", "ball", "sport"], .activities),
        EmojiItem("🏈", "American Football", ["nfl", "superbowl"], .activities),
        EmojiItem("⚾", "Baseball", ["mlb", "sport"], .activities),
        EmojiItem("🥎", "Softball", ["ball", "sport"], .activities),
        EmojiItem("🎾", "Tennis", ["racket", "court", "sport"], .activities),
        EmojiItem("🏐", "Volleyball", ["beach", "sport"], .activities),
        EmojiItem("🏉", "Rugby Football", ["rugby", "sport"], .activities),
        EmojiItem("🥏", "Flying Disc", ["frisbee", "disc"], .activities),
        EmojiItem("🎱", "Pool 8 Ball", ["billiards", "pool", "game"], .activities),
        EmojiItem("🪀", "Yo-Yo", ["toy", "game"], .activities),
        EmojiItem("🏓", "Ping Pong", ["table tennis", "paddle"], .activities),
        EmojiItem("🏸", "Badminton", ["racket", "shuttlecock", "sport"], .activities),
        EmojiItem("🏒", "Ice Hockey", ["nhl", "puck"], .activities),
        EmojiItem("🏑", "Field Hockey", ["hockey", "sport"], .activities),
        EmojiItem("🏏", "Cricket", ["bat", "ball", "bangladesh", "tigers", "match"], .activities),
        EmojiItem("🥊", "Boxing Glove", ["punch", "fight", "boxer"], .activities),
        EmojiItem("🥋", "Martial Arts Uniform", ["karate", "judo", "taekwondo"], .activities),
        EmojiItem("🎯", "Bullseye", ["dart", "target", "accurate"], .activities),
        EmojiItem("⛳", "Flag in Hole", ["golf", "course"], .activities),
        EmojiItem("⛸️", "Ice Skate", ["skating", "winter"], .activities),
        EmojiItem("🎣", "Fishing Pole", ["fish", "hook", "river"], .activities),
        EmojiItem("🤿", "Diving Mask", ["scuba", "snorkel", "swim"], .activities),
        EmojiItem("🎮", "Video Game", ["controller", "playstation", "xbox", "gaming"], .activities),
        EmojiItem("🕹️", "Joystick", ["arcade", "retro", "game"], .activities),
        EmojiItem("🎲", "Game Die", ["dice", "ludo", "boardgame", "chance"], .activities),
        EmojiItem("♟️", "Chess Pawn", ["chess", "strategy", "game"], .activities),
        EmojiItem("🏆", "Trophy", ["champion", "winner", "first", "gold"], .activities),
        EmojiItem("🥇", "1st Place Medal", ["gold", "win", "first"], .activities),
        EmojiItem("🥈", "2nd Place Medal", ["silver", "second"], .activities),
        EmojiItem("🥉", "3rd Place Medal", ["bronze", "third"], .activities),

        // MARK: - Travel & Places
        EmojiItem("🚗", "Automobile", ["car", "drive", "gari"], .travel),
        EmojiItem("🚕", "Taxi", ["cab", "ride", "uber"], .travel),
        EmojiItem("🚙", "Sport Utility Vehicle", ["suv", "car"], .travel),
        EmojiItem("🚌", "Bus", ["transit", "school bus"], .travel),
        EmojiItem("🚎", "Trolleybus", ["bus", "electric"], .travel),
        EmojiItem("🏎️", "Racing Car", ["f1", "race", "speed"], .travel),
        EmojiItem("🚓", "Police Car", ["cop", "siren"], .travel),
        EmojiItem("🚑", "Ambulance", ["hospital", "emergency"], .travel),
        EmojiItem("🚒", "Fire Engine", ["fire truck", "emergency"], .travel),
        EmojiItem("🚐", "Minibus", ["van", "transit"], .travel),
        EmojiItem("🚚", "Delivery Truck", ["package", "cargo"], .travel),
        EmojiItem("🚛", "Articulated Lorry", ["semi", "truck"], .travel),
        EmojiItem("🚜", "Tractor", ["farm", "agriculture"], .travel),
        EmojiItem("🦯", "White Cane", ["blind", "guide"], .travel),
        EmojiItem("🦽", "Manual Wheelchair", ["access", "mobility"], .travel),
        EmojiItem("🦼", "Motorized Wheelchair", ["access"], .travel),
        EmojiItem("🛴", "Kick Scooter", ["scooter", "ride"], .travel),
        EmojiItem("🚲", "Bicycle", ["bike", "cycle", "ride"], .travel),
        EmojiItem("🛵", "Motor Scooter", ["moped", "scooter"], .travel),
        EmojiItem("🏍️", "Motorcycle", ["bike", "harley", "speed"], .travel),
        EmojiItem("🛺", "Auto Rickshaw", ["cng", "tuk tuk", "rickshaw", "dhaka"], .travel),
        EmojiItem("🚨", "Police Car Light", ["emergency", "alert", "warning"], .travel),
        EmojiItem("🛩️", "Small Airplane", ["plane", "flight"], .travel),
        EmojiItem("✈️", "Airplane", ["flight", "travel", "fly", "airport"], .travel),
        EmojiItem("🛫", "Airplane Departure", ["takeoff", "fly"], .travel),
        EmojiItem("🛬", "Airplane Arrival", ["landing"], .travel),
        EmojiItem("🚀", "Rocket", ["space", "launch", "moon", "future"], .travel),
        EmojiItem("🛸", "Flying Saucer", ["ufo", "alien"], .travel),
        EmojiItem("🚁", "Helicopter", ["chopper", "flight"], .travel),
        EmojiItem("⛵", "Sailboat", ["boat", "sea", "yacht", "nouka"], .travel),
        EmojiItem("🚤", "Speedboat", ["fast", "water", "boat"], .travel),
        EmojiItem("🛳️", "Passenger Ship", ["cruise", "titanic", "launch"], .travel),

        // MARK: - Objects
        EmojiItem("📱", "Mobile Phone", ["iphone", "cellphone", "android"], .objects),
        EmojiItem("📲", "Mobile Phone with Arrow", ["call", "message"], .objects),
        EmojiItem("💻", "Laptop", ["macbook", "computer", "pc", "work"], .objects),
        EmojiItem("⌨️", "Keyboard", ["typing", "lekhi", "avro", "mechanical"], .objects),
        EmojiItem("🖥️", "Desktop Computer", ["imac", "screen"], .objects),
        EmojiItem("🖨️", "Printer", ["paper", "print"], .objects),
        EmojiItem("🖱️", "Computer Mouse", ["click", "hardware"], .objects),
        EmojiItem("💽", "Computer Disk", ["minidisc", "data"], .objects),
        EmojiItem("💾", "Floppy Disk", ["save", "disk", "retro"], .objects),
        EmojiItem("💿", "Optical Disk", ["cd", "dvd"], .objects),
        EmojiItem("📀", "DVD", ["movie", "disc"], .objects),
        EmojiItem("📷", "Camera", ["photo", "picture", "lens"], .objects),
        EmojiItem("📸", "Camera with Flash", ["photo", "flash"], .objects),
        EmojiItem("📹", "Video Camera", ["movie", "camcorder"], .objects),
        EmojiItem("🎥", "Movie Camera", ["cinema", "film"], .objects),
        EmojiItem("📽️", "Film Projector", ["cinema", "movie"], .objects),
        EmojiItem("📺", "Television", ["tv", "show", "screen"], .objects),
        EmojiItem("📻", "Radio", ["broadcast", "fm", "music"], .objects),
        EmojiItem("🎙️", "Studio Microphone", ["podcast", "record", "audio"], .objects),
        EmojiItem("🎚️", "Level Slider", ["music", "volume"], .objects),
        EmojiItem("🎛️", "Control Knobs", ["audio", "dj"], .objects),
        EmojiItem("⏱️", "Stopwatch", ["time", "timer", "speed"], .objects),
        EmojiItem("⏲️", "Timer Clock", ["alarm", "cook"], .objects),
        EmojiItem("⏰", "Alarm Clock", ["wake up", "morning", "time"], .objects),
        EmojiItem("🕰️", "Mantelpiece Clock", ["vintage", "time"], .objects),
        EmojiItem("⌛", "Hourglass Done", ["time", "sand"], .objects),
        EmojiItem("⏳", "Hourglass Not Done", ["loading", "wait", "time"], .objects),
        EmojiItem("📡", "Satellite Antenna", ["signal", "space", "dish"], .objects),
        EmojiItem("🔋", "Battery", ["power", "charge", "energy"], .objects),
        EmojiItem("🔌", "Electric Plug", ["power", "outlet", "cable"], .objects),
        EmojiItem("💡", "Light Bulb", ["idea", "bright", "smart", "light"], .objects),
        EmojiItem("🔦", "Flashlight", ["torch", "light", "dark"], .objects),
        EmojiItem("🕯️", "Candle", ["flame", "wax", "light"], .objects),
        EmojiItem("🧯", "Fire Extinguisher", ["fire", "safety"], .objects),
        EmojiItem("🗑️", "Wastebasket", ["trash", "bin", "garbage"], .objects),
        EmojiItem("🪑", "Chair", ["seat", "sit"], .objects),
        EmojiItem("🚪", "Door", ["entrance", "exit"], .objects),
        EmojiItem("🛏️", "Bed", ["sleep", "rest", "hotel"], .objects),
        EmojiItem("🛋️", "Couch and Lamp", ["sofa", "living room"], .objects),
        EmojiItem("🧸", "Teddy Bear", ["toy", "plush", "cute"], .objects),
        EmojiItem("🖼️", "Framed Picture", ["art", "painting", "museum"], .objects),
        EmojiItem("🛍️", "Shopping Bags", ["mall", "buy", "store"], .objects),
        EmojiItem("🛒", "Shopping Cart", ["buy", "store", "supermarket"], .objects),
        EmojiItem("🎁", "Wrapped Gift", ["present", "birthday", "box", "gift"], .objects),
        EmojiItem("🎈", "Balloon", ["party", "celebration", "air"], .objects),
        EmojiItem("🎉", "Party Popper", ["tada", "celebrate", "congrats", "party"], .objects),
        EmojiItem("🎊", "Confetti Ball", ["party", "celebration"], .objects),
        EmojiItem("🪄", "Magic Wand", ["magic", "spell", "wizard"], .objects),
        EmojiItem("🔮", "Crystal Ball", ["future", "fortune", "magic"], .objects),
        EmojiItem("🧿", "Nazar Amulet", ["evil eye", "protection", "nazar"], .objects),
        EmojiItem("🕹️", "Joystick", ["retro", "arcade", "game"], .objects),
        EmojiItem("🪞", "Mirror", ["reflection", "glass"], .objects),
        EmojiItem("💎", "Gem Stone", ["diamond", "jewel", "rich", "crystal"], .objects),
        EmojiItem("🔔", "Bell", ["notification", "ring", "sound"], .objects),
        EmojiItem("🔕", "Bell with Slash", ["mute", "silent", "quiet"], .objects),
        EmojiItem("📣", "Megaphone", ["cheer", "shout", "announce"], .objects),
        EmojiItem("📢", "Loudspeaker", ["announcement", "sound"], .objects),
        EmojiItem("📮", "Postbox", ["mail", "letter"], .objects),
        EmojiItem("📪", "Closed Mailbox with Lowered Flag", ["inbox", "mail"], .objects),
        EmojiItem("📫", "Closed Mailbox with Raised Flag", ["mail", "post"], .objects),
        EmojiItem("📬", "Open Mailbox with Raised Flag", ["mail", "incoming"], .objects),
        EmojiItem("📭", "Open Mailbox with Lowered Flag", ["empty mailbox"], .objects),
        EmojiItem("📦", "Package", ["box", "delivery", "shipping"], .objects),
        EmojiItem("📧", "E-Mail", ["email", "message", "letter"], .objects),
        EmojiItem("✉️", "Envelope", ["mail", "letter", "postal"], .objects),
        EmojiItem("📩", "Envelope with Arrow", ["incoming mail"], .objects),
        EmojiItem("📨", "Incoming Envelope", ["mail", "receive"], .objects),
        EmojiItem("🏷️", "Label", ["tag", "price", "sale"], .objects),
        EmojiItem("📜", "Scroll", ["ancient", "paper", "document"], .objects),
        EmojiItem("📄", "Page Facing Up", ["document", "file", "paper"], .objects),
        EmojiItem("📰", "Newspaper", ["news", "press", "daily"], .objects),
        EmojiItem("📑", "Bookmark Tabs", ["notes", "organize"], .objects),
        EmojiItem("📊", "Bar Chart", ["graph", "stats", "data", "analytics"], .objects),
        EmojiItem("📈", "Chart Increasing", ["growth", "up", "stocks", "profit"], .objects),
        EmojiItem("📉", "Chart Decreasing", ["down", "loss", "recession"], .objects),
        EmojiItem("📋", "Clipboard", ["paste", "copy", "notes", "task"], .objects),
        EmojiItem("📌", "Pushpin", ["pin", "notice", "location"], .objects),
        EmojiItem("📍", "Round Pushpin", ["location", "pin", "map", "here"], .objects),
        EmojiItem("📎", "Paperclip", ["attachment", "clip", "office"], .objects),
        EmojiItem("🖇️", "Linked Paperclips", ["clips", "link"], .objects),
        EmojiItem("📏", "Straight Ruler", ["measure", "length"], .objects),
        EmojiItem("📐", "Triangular Ruler", ["geometry", "math"], .objects),
        EmojiItem("✂️", "Scissors", ["cut", "tool", "snip"], .objects),
        EmojiItem("🗃️", "Card File Box", ["archive", "data"], .objects),
        EmojiItem("🗄️", "File Cabinet", ["storage", "office"], .objects),
        EmojiItem("🗑️", "Wastebasket", ["trash", "bin"], .objects),
        EmojiItem("🔒", "Locked", ["secure", "password", "privacy", "lock"], .objects),
        EmojiItem("🔓", "Unlocked", ["open", "security", "access"], .objects),
        EmojiItem("🔏", "Locked with Pen", ["privacy", "sign"], .objects),
        EmojiItem("🔐", "Locked with Key", ["secure", "secret"], .objects),
        EmojiItem("🔑", "Key", ["door", "unlock", "access", "password"], .objects),
        EmojiItem("🗝️", "Old Key", ["vintage", "clue", "key"], .objects),
        EmojiItem("🔨", "Hammer", ["tool", "build", "fix"], .objects),
        EmojiItem("🪓", "Axe", ["wood", "chop", "tool"], .objects),
        EmojiItem("⛏️", "Pick", ["mine", "minecraft", "tool"], .objects),
        EmojiItem("⚒️", "Hammer and Pick", ["mining", "tools"], .objects),
        EmojiItem("🛠️", "Hammer and Wrench", ["settings", "repair", "fix"], .objects),
        EmojiItem("🗡️", "Dagger", ["knife", "weapon"], .objects),
        EmojiItem("⚔️", "Crossed Swords", ["battle", "fight", "war"], .objects),
        EmojiItem("💣", "Bomb", ["explosion", "boom", "danger"], .objects),
        EmojiItem("🪃", "Boomerang", ["return", "australia"], .objects),
        EmojiItem("🏹", "Bow and Arrow", ["archery", "sagittarius"], .objects),
        EmojiItem("🛡️", "Shield", ["defense", "protect", "security"], .objects),
        EmojiItem("🪚", "Carpentry Saw", ["wood", "cut"], .objects),
        EmojiItem("🔧", "Wrench", ["spanner", "fix", "repair"], .objects),
        EmojiItem("🪛", "Screwdriver", ["tool", "tighten"], .objects),
        EmojiItem("🔩", "Nut and Bolt", ["hardware", "screw"], .objects),
        EmojiItem("⚙️", "Gear", ["settings", "cog", "options", "preferences"], .objects),
        EmojiItem("🗜️", "Clamp", ["tool", "hold"], .objects),
        EmojiItem("⚖️", "Balance Scale", ["justice", "law", "weight"], .objects),
        EmojiItem("🦯", "White Cane", ["blind", "walk"], .objects),
        EmojiItem("🔗", "Link", ["url", "hyperlink", "connection"], .objects),
        EmojiItem("⛓️", "Chains", ["metal", "locked", "blockchain"], .objects),
        EmojiItem("🪝", "Hook", ["catch", "fish"], .objects),
        EmojiItem("🧰", "Toolbox", ["tools", "repair"], .objects),
        EmojiItem("🧲", "Magnet", ["attraction", "magnetic"], .objects),
        EmojiItem("🪜", "Ladder", ["climb", "height"], .objects),
        EmojiItem("🧪", "Test Tube", ["science", "chemistry", "lab"], .objects),
        EmojiItem("🧫", "Petri Dish", ["biology", "bacteria"], .objects),
        EmojiItem("🧬", "DNA", ["genetics", "biology", "life"], .objects),
        EmojiItem("🔬", "Microscope", ["science", "lab", "investigate"], .objects),
        EmojiItem("🔭", "Telescope", ["astronomy", "stars", "space"], .objects),
        EmojiItem("📡", "Satellite Antenna", ["signal", "radar"], .objects),
        EmojiItem("💉", "Syringe", ["vaccine", "shot", "injection", "doctor"], .objects),
        EmojiItem("🩸", "Drop of Blood", ["blood", "donation", "red"], .objects),
        EmojiItem("💊", "Pill", ["medicine", "doctor", "health", "drug"], .objects),
        EmojiItem("🩹", "Adhesive Bandage", ["bandaid", "heal", "wound"], .objects),
        EmojiItem("🩺", "Stethoscope", ["doctor", "health", "hospital"], .objects),
        EmojiItem("🚪", "Door", ["entrance", "exit"], .objects),
        EmojiItem("🪟", "Window", ["glass", "view"], .objects),
        EmojiItem("🪞", "Mirror", ["look", "beauty"], .objects),
        EmojiItem("🪠", "Plunger", ["toilet", "clean"], .objects),
        EmojiItem("🧼", "Soap", ["clean", "wash", "bubble"], .objects),
        EmojiItem("🧽", "Sponge", ["clean", "absorb"], .objects),
        EmojiItem("🧴", "Lotion Bottle", ["cream", "skincare", "moisturizer"], .objects),
        EmojiItem("🧻", "Roll of Paper", ["toilet paper", "tissue"], .objects),
        EmojiItem("🧹", "Broom", ["sweep", "clean"], .objects),
        EmojiItem("🧺", "Basket", ["laundry", "picnic"], .objects),
        EmojiItem("🧦", "Socks", ["clothing", "feet", "warm"], .objects),
        EmojiItem("🧤", "Gloves", ["winter", "warm", "hands"], .objects),
        EmojiItem("🧣", "Scarf", ["winter", "neck", "warm"], .objects),
        EmojiItem("👖", "Jeans", ["pants", "denim"], .objects),
        EmojiItem("👕", "T-Shirt", ["shirt", "clothes", "apparel"], .objects),
        EmojiItem("👔", "Necktie", ["tie", "suit", "formal", "business"], .objects),
        EmojiItem("👗", "Dress", ["clothing", "fashion"], .objects),
        EmojiItem("👘", "Kimono", ["japanese", "dress"], .objects),
        EmojiItem("🥻", "Sari", ["shari", "bengali", "dress", "tradition", "bangladesh"], .objects),
        EmojiItem("🩱", "One-Piece Swimsuit", ["swim", "beach"], .objects),
        EmojiItem("🩲", "Briefs", ["underwear"], .objects),
        EmojiItem("🩳", "Shorts", ["pants", "summer"], .objects),
        EmojiItem("👙", "Bikini", ["swim", "beach"], .objects),
        EmojiItem("👠", "High-Heeled Shoe", ["heels", "fashion", "shoes"], .objects),
        EmojiItem("👡", "Woman’s Sandal", ["sandal", "shoes"], .objects),
        EmojiItem("👢", "Woman’s Boot", ["boots", "shoes"], .objects),
        EmojiItem("👞", "Man’s Shoe", ["formal", "leather", "shoes"], .objects),
        EmojiItem("👟", "Running Shoe", ["sneakers", "nike", "gym", "shoes"], .objects),
        EmojiItem("🥾", "Hiking Boot", ["trail", "outdoor", "walk"], .objects),
        EmojiItem("🥿", "Flat Shoe", ["shoes", "slipon"], .objects),
        EmojiItem("👑", "Crown", ["king", "queen", "royalty", "gold"], .objects),
        EmojiItem("👒", "Woman’s Hat", ["fashion", "summer"], .objects),
        EmojiItem("🎩", "Top Hat", ["formal", "magic", "gentleman"], .objects),
        EmojiItem("🎓", "Graduation Cap", ["degree", "college", "university", "study"], .objects),
        EmojiItem("🧢", "Billed Cap", ["hat", "baseball"], .objects),
        EmojiItem("🪖", "Military Helmet", ["soldier", "army"], .objects),
        EmojiItem("💄", "Lipstick", ["makeup", "cosmetics", "beauty"], .objects),
        EmojiItem("💍", "Ring", ["diamond", "wedding", "engage", "love", "propose"], .objects),
        EmojiItem("💼", "Briefcase", ["business", "work", "job"], .objects),

        // MARK: - Symbols
        EmojiItem("❤️", "Red Heart", ["love", "romance", "heart", "like", "favorite", "bhalobasha"], .symbols),
        EmojiItem("🧡", "Orange Heart", ["love", "friendship", "orange"], .symbols),
        EmojiItem("💛", "Yellow Heart", ["love", "friendship", "yellow"], .symbols),
        EmojiItem("💚", "Green Heart", ["love", "nature", "green"], .symbols),
        EmojiItem("💙", "Blue Heart", ["love", "peace", "blue"], .symbols),
        EmojiItem("💜", "Purple Heart", ["love", "royal", "purple"], .symbols),
        EmojiItem("🖤", "Black Heart", ["dark", "goth", "sorrow"], .symbols),
        EmojiItem("🤍", "White Heart", ["pure", "peace", "white"], .symbols),
        EmojiItem("🤎", "Brown Heart", ["coffee", "earth"], .symbols),
        EmojiItem("💔", "Broken Heart", ["breakup", "sad", "hurt", "pain"], .symbols),
        EmojiItem("❣️", "Heart Exclamation", ["love", "emphasis"], .symbols),
        EmojiItem("💕", "Two Hearts", ["love", "affection"], .symbols),
        EmojiItem("💞", "Revolving Hearts", ["love", "hearts"], .symbols),
        EmojiItem("💓", "Beating Heart", ["heartbeat", "alive", "love"], .symbols),
        EmojiItem("💗", "Growing Heart", ["sparkle", "love"], .symbols),
        EmojiItem("💖", "Sparkling Heart", ["sparkle", "love", "shine"], .symbols),
        EmojiItem("💘", "Heart with Arrow", ["cupid", "love"], .symbols),
        EmojiItem("💝", "Heart with Ribbon", ["gift", "valentine", "love"], .symbols),
        EmojiItem("💟", "Heart Decoration", ["purple", "heart"], .symbols),
        EmojiItem("☮️", "Peace Symbol", ["peace", "calm"], .symbols),
        EmojiItem("✝️", "Latin Cross", ["christian", "religion"], .symbols),
        EmojiItem("☪️", "Star and Crescent", ["islam", "muslim", "religion"], .symbols),
        EmojiItem("🕉️", "Om", ["hindu", "religion", "mantra"], .symbols),
        EmojiItem("☸️", "Wheel of Dharma", ["buddhist", "religion"], .symbols),
        EmojiItem("✡️", "Star of David", ["jewish", "religion"], .symbols),
        EmojiItem("☯️", "Yin Yang", ["balance", "taoist"], .symbols),
        EmojiItem("🕎", "Menorah", ["hanukkah", "jewish"], .symbols),
        EmojiItem("💯", "Hundred Points", ["perfect", "score", "100", "agree"], .symbols),
        EmojiItem("♨️", "Hot Springs", ["hot", "steam", "bath"], .symbols),
        EmojiItem("💥", "Collision", ["boom", "explode", "impact"], .symbols),
        EmojiItem("💫", "Dizzy", ["star", "sparkle", "magic"], .symbols),
        EmojiItem("💦", "Sweat Droplets", ["water", "splashing", "workout"], .symbols),
        EmojiItem("💨", "Dashing Away", ["fast", "run", "speed", "wind"], .symbols),
        EmojiItem("✨", "Sparkles", ["magic", "stars", "shine", "clean", "ai", "new"], .symbols),
        EmojiItem("🔥", "Fire", ["flame", "lit", "hot", "trend", "fire"], .symbols),
        EmojiItem("⭐", "Star", ["favorite", "gold", "rating"], .symbols),
        EmojiItem("🌟", "Glowing Star", ["shine", "sparkle"], .symbols),
        EmojiItem("⚡", "High Voltage", ["lightning", "thunder", "power", "energy", "fast"], .symbols),
        EmojiItem("☄️", "Comet", ["meteor", "space"], .symbols),
        EmojiItem("☀️", "Sun", ["sunny", "weather", "summer", "warm"], .symbols),
        EmojiItem("🌙", "Crescent Moon", ["night", "moon", "eid", "ramadan"], .symbols),
        EmojiItem("🌈", "Rainbow", ["pride", "colors", "weather", "sky"], .symbols),
        EmojiItem("☁️", "Cloud", ["weather", "sky", "cloudy"], .symbols),
        EmojiItem("🌧️", "Cloud with Rain", ["rain", "storm", "bristi"], .symbols),
        EmojiItem("⛈️", "Cloud with Lightning and Rain", ["thunderstorm", "weather"], .symbols),
        EmojiItem("❄️", "Snowflake", ["cold", "winter", "ice", "snow"], .symbols),
        EmojiItem("☃️", "Snowman", ["winter", "snow"], .symbols),
        EmojiItem("💧", "Droplet", ["water", "drop", "liquid"], .symbols),
        EmojiItem("🌊", "Water Wave", ["ocean", "sea", "tsunami", "surf"], .symbols),
        EmojiItem("✅", "Check Mark Button", ["done", "yes", "correct", "success", "tick"], .symbols),
        EmojiItem("❌", "Cross Mark", ["no", "cancel", "wrong", "delete", "error"], .symbols),
        EmojiItem("❓", "Question Mark", ["what", "help", "confused", "ask"], .symbols),
        EmojiItem("❗", "Exclamation Mark", ["warning", "alert", "important"], .symbols),
        EmojiItem("⚠️", "Warning", ["caution", "danger", "alert"], .symbols),
        EmojiItem("⛔", "No Entry", ["stop", "forbidden", "denied"], .symbols),
        EmojiItem("🚫", "Prohibited", ["ban", "no", "forbidden"], .symbols),
        EmojiItem("🔞", "No One Under Eighteen", ["18", "adult"], .symbols),
        EmojiItem("🛑", "Stop Sign", ["halt", "stop", "red"], .symbols),
        EmojiItem("🎵", "Musical Note", ["music", "song", "tune", "gan"], .symbols),
        EmojiItem("🎶", "Musical Notes", ["music", "singing", "audio"], .symbols),
        EmojiItem("➕", "Plus", ["add", "math"], .symbols),
        EmojiItem("➖", "Minus", ["subtract", "math"], .symbols),
        EmojiItem("✖️", "Multiply", ["times", "math"], .symbols),
        EmojiItem("➗", "Divide", ["division", "math"], .symbols),
        EmojiItem("♾️", "Infinity", ["forever", "endless"], .symbols),
        EmojiItem("💲", "Heavy Dollar Sign", ["money", "currency", "usd"], .symbols),
        EmojiItem("💱", "Currency Exchange", ["forex", "money"], .symbols),

        // MARK: - Flags
        EmojiItem("🇧🇩", "Flag: Bangladesh", ["bangladesh", "dhaka", "desh", "bd", "flag"], .flags),
        EmojiItem("🇮🇳", "Flag: India", ["india", "delhi", "flag"], .flags),
        EmojiItem("🇵🇰", "Flag: Pakistan", ["pakistan", "flag"], .flags),
        EmojiItem("🇺🇸", "Flag: United States", ["usa", "america", "flag"], .flags),
        EmojiItem("🇬🇧", "Flag: United Kingdom", ["uk", "britain", "england", "london", "flag"], .flags),
        EmojiItem("🇨🇦", "Flag: Canada", ["canada", "toronto", "flag"], .flags),
        EmojiItem("🇦🇺", "Flag: Australia", ["australia", "sydney", "flag"], .flags),
        EmojiItem("🇩🇪", "Flag: Germany", ["germany", "berlin", "flag"], .flags),
        EmojiItem("🇫🇷", "Flag: France", ["france", "paris", "flag"], .flags),
        EmojiItem("🇮🇹", "Flag: Italy", ["italy", "rome", "flag"], .flags),
        EmojiItem("🇯🇵", "Flag: Japan", ["japan", "tokyo", "flag"], .flags),
        EmojiItem("🇰🇷", "Flag: South Korea", ["korea", "seoul", "flag"], .flags),
        EmojiItem("🇨🇳", "Flag: China", ["china", "beijing", "flag"], .flags),
        EmojiItem("🇸🇦", "Flag: Saudi Arabia", ["saudi", "makkah", "riyadh", "flag"], .flags),
        EmojiItem("🇦🇪", "Flag: United Arab Emirates", ["uae", "dubai", "flag"], .flags),
        EmojiItem("🇹🇷", "Flag: Turkey", ["turkey", "istanbul", "flag"], .flags),
        EmojiItem("🇲🇾", "Flag: Malaysia", ["malaysia", "flag"], .flags),
        EmojiItem("🇸🇬", "Flag: Singapore", ["singapore", "flag"], .flags),
        EmojiItem("🇧🇷", "Flag: Brazil", ["brazil", "flag"], .flags),
        EmojiItem("🇦🇷", "Flag: Argentina", ["argentina", "messi", "flag"], .flags),
        EmojiItem("🇵🇸", "Flag: Palestinian Territories", ["palestine", "flag"], .flags),
        EmojiItem("🏁", "Chequered Flag", ["race", "finish", "winner"], .flags),
        EmojiItem("🚩", "Triangular Flag", ["red flag", "warning"], .flags),
        EmojiItem("🎌", "Crossed Flags", ["japan", "celebration"], .flags),
        EmojiItem("🏴‍☠️", "Pirate Flag", ["jolly roger", "skull"], .flags)
    ]

    public static func items(for category: EmojiCategory) -> [EmojiItem] {
        all.filter { $0.category == category }
    }

    public static func search(query: String) -> [EmojiItem] {
        let q = query.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if q.isEmpty { return all }
        return all.filter { $0.matches(query: q) }
    }
}
